#!/usr/bin/env bash
set -Eeuo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="${APP_DIR:-/opt/memory-server-infra/hindsight}"; SOURCE_DIR="${ROOT_DIR}/docker/hindsight"; ENV_FILE="${APP_DIR}/.env"; CODEX_AUTH_DIR_DEFAULT="/var/lib/hindsight/codex"; HINDSIGHT_SECRET_DIR="${APP_DIR}/secrets/codex"; CODEX_DEFAULT_MODEL="${CODEX_DEFAULT_MODEL:-gpt-5.6-luna}"
XRAY_HTTP_PROXY="${XRAY_HTTP_PROXY:-http://127.0.0.1:10809}"; XRAY_SOCKS_PROXY="${XRAY_SOCKS_PROXY:-socks5h://127.0.0.1:10808}"
log(){ printf '\n[INFO] %s\n' "$*"; }; warn(){ printf '\n[WARN] %s\n' "$*" >&2; }; die(){ printf '\n[ERROR] %s\n' "$*" >&2; exit 1; }
[[ ${EUID} -eq 0 ]] || die "请使用 sudo/root 运行。"
command -v docker >/dev/null 2>&1 || die "未检测到 Docker。"; docker compose version >/dev/null 2>&1 || die "未检测到 Docker Compose plugin。"; systemctl is-active --quiet docker || die "Docker 服务未运行。"; systemctl is-active --quiet xray || die "Xray 服务未运行。"
[[ -f "${SOURCE_DIR}/compose.yml" && -f "${SOURCE_DIR}/.env.example" ]] || die "仓库中的 Hindsight 模板不完整。"
MEM_MB="$(awk '/^MemTotal:/ {printf "%d", $2/1024}' /proc/meminfo)"; SWAP_MB="$(awk '/^SwapTotal:/ {printf "%d", $2/1024}' /proc/meminfo)"; FREE_MB="$(df -Pm /var/lib/docker 2>/dev/null | awk 'NR==2 {print $4}')"; [[ -n "$FREE_MB" ]] || FREE_MB="$(df -Pm / | awk 'NR==2 {print $4}')"
log "部署前资源：RAM ${MEM_MB} MB / Swap ${SWAP_MB} MB / Docker 所在分区可用约 ${FREE_MB} MB。"; (( MEM_MB >= 4096 )) || warn "RAM 低于 Hindsight 官方建议的 4GB；将依赖低并发 + Swap 做实验性部署。"; (( MEM_MB >= 4096 || SWAP_MB >= 2048 )) || die "低内存机器当前 Swap 也不足 2GB，请先运行 01-system-init.sh。"
mkdir -p "$APP_DIR"; install -m 0644 "${SOURCE_DIR}/compose.yml" "${APP_DIR}/compose.yml"
get_env(){ local key="$1"; [[ -f "$ENV_FILE" ]] || return 0; awk -F= -v k="$key" '$1==k {sub(/^[^=]*=/,""); print; exit}' "$ENV_FILE"; }
write_env_value(){ local key="$1" value="$2" tmp; tmp="$(mktemp)"; awk -F= -v k="$key" -v v="$value" 'BEGIN{done=0} $1==k {print k "=" v; done=1; next} {print} END{if(!done) print k "=" v}' "$ENV_FILE" >"$tmp"; install -m 0600 "$tmp" "$ENV_FILE"; rm -f "$tmp"; }
first_config_wizard(){ install -m 0600 "${SOURCE_DIR}/.env.example" "$ENV_FILE"; cat <<'EOF'

========== Hindsight LLM 首次配置 ==========
请选择 Hindsight 使用的 LLM 认证方式：
  [1] ChatGPT / Codex OAuth（推荐）
  [2] LLM API Key
EOF
local choice provider model api_key; while true; do read -r -p "请输入 [1/2]: " choice; case "$choice" in 1) write_env_value HINDSIGHT_API_LLM_PROVIDER "openai-codex"; write_env_value HINDSIGHT_API_LLM_MODEL "$CODEX_DEFAULT_MODEL"; write_env_value HINDSIGHT_API_LLM_API_KEY ""; write_env_value CODEX_HOME "$CODEX_AUTH_DIR_DEFAULT"; break;; 2) read -r -p "Provider: " provider; read -r -p "Model: " model; read -r -s -p "API Key: " api_key; echo; [[ -n "$provider" && -n "$model" && -n "$api_key" ]] || { warn "配置不能为空。"; continue; }; write_env_value HINDSIGHT_API_LLM_PROVIDER "$provider"; write_env_value HINDSIGHT_API_LLM_MODEL "$model"; write_env_value HINDSIGHT_API_LLM_API_KEY "$api_key"; unset api_key; break;; *) warn "请输入 1 或 2。";; esac; done; }
[[ -f "$ENV_FILE" ]] || first_config_wizard; chmod 600 "$ENV_FILE"; PROVIDER="$(get_env HINDSIGHT_API_LLM_PROVIDER)"; API_KEY="$(get_env HINDSIGHT_API_LLM_API_KEY)"; [[ -n "$PROVIDER" ]] || die "${ENV_FILE} 中缺少 HINDSIGHT_API_LLM_PROVIDER。"
if [[ "$PROVIDER" == openai-codex ]]; then CURRENT_MODEL="$(get_env HINDSIGHT_API_LLM_MODEL)"; case "$CURRENT_MODEL" in ""|gpt-5.4-mini|gpt-5.6-terra) write_env_value HINDSIGHT_API_LLM_MODEL "$CODEX_DEFAULT_MODEL"; log "Codex 默认模型已迁移为 ${CODEX_DEFAULT_MODEL}（原配置 ${CURRENT_MODEL:-为空}）。";; *) log "保留用户显式配置的 Codex 模型：${CURRENT_MODEL}";; esac; fi
find_user_command(){ local name="$1" path="" sudo_user="${SUDO_USER:-}"; path="$(command -v "$name" 2>/dev/null || true)"; [[ -n "$path" ]] && { printf '%s\n' "$path"; return; }; if [[ -n "$sudo_user" && "$sudo_user" != root ]]; then path="$(sudo -Hiu "$sudo_user" bash -lc "command -v $name" 2>/dev/null | tail -n1 || true)"; [[ -n "$path" && -x "$path" ]] && { printf '%s\n' "$path"; return; }; fi; return 1; }
run_node_cli(){ local bin="$1"; shift; env PATH="$(dirname "$bin"):${PATH}" "$bin" "$@"; }
install_codex_cli(){ local codex_bin npm_bin npm_dir install_path; codex_bin="$(find_user_command codex || true)"; [[ -z "$codex_bin" ]] || { log "Codex CLI 已安装：$(run_node_cli "$codex_bin" --version)"; return; }; npm_bin="$(find_user_command npm || true)"; [[ -n "$npm_bin" ]] || die "未检测到 npm。"; if [[ -n "${SUDO_USER:-}" && "$SUDO_USER" != root && "$npm_bin" == /home/* ]]; then npm_dir="$(dirname "$npm_bin")"; install_path="PATH=${npm_dir}:\$PATH"; sudo -Hiu "$SUDO_USER" bash -lc "$install_path '$npm_bin' install -g @openai/codex" || sudo -Hiu "$SUDO_USER" bash -lc "HTTP_PROXY=$XRAY_HTTP_PROXY HTTPS_PROXY=$XRAY_HTTP_PROXY $install_path '$npm_bin' install -g @openai/codex" || die "Codex CLI 安装失败。"; else run_node_cli "$npm_bin" install -g @openai/codex || HTTP_PROXY="$XRAY_HTTP_PROXY" HTTPS_PROXY="$XRAY_HTTP_PROXY" run_node_cli "$npm_bin" install -g @openai/codex || die "Codex CLI 安装失败。"; fi; }
run_codex_oauth(){ local codex_bin="$1" auth_dir="$2"; echo "========== ChatGPT / Codex 一次性授权 =========="; HTTP_PROXY="$XRAY_HTTP_PROXY" HTTPS_PROXY="$XRAY_HTTP_PROXY" ALL_PROXY="$XRAY_SOCKS_PROXY" CODEX_HOME="$auth_dir" PATH="$(dirname "$codex_bin"):${PATH}" "$codex_bin" login --device-auth || die "Codex OAuth 授权未成功完成。"; [[ -s "$auth_dir/auth.json" ]] || die "授权后未找到 auth.json。"; chmod 600 "$auth_dir/auth.json"; }
prepare_hindsight_codex_auth(){ local source_auth="$1" image_tag="$2" runtime_id runtime_uid runtime_gid target_auth; runtime_id="$(docker run --rm --entrypoint sh "ghcr.io/vectorize-io/hindsight:${image_tag}" -c 'id -u; id -g')" || die "无法读取 Hindsight 镜像运行 UID/GID。"; runtime_uid="$(printf '%s\n' "$runtime_id" | sed -n '1p')"; runtime_gid="$(printf '%s\n' "$runtime_id" | sed -n '2p')"; [[ "$runtime_uid" =~ ^[0-9]+$ && "$runtime_gid" =~ ^[0-9]+$ ]] || die "Hindsight UID/GID 检测异常：${runtime_id}"; install -d -m 0700 -o "$runtime_uid" -g "$runtime_gid" "$HINDSIGHT_SECRET_DIR"; target_auth="$HINDSIGHT_SECRET_DIR/auth.json"; if [[ "$source_auth" != "$target_auth" && ! -s "$target_auth" ]]; then install -m 0600 -o "$runtime_uid" -g "$runtime_gid" "$source_auth" "$target_auth"; fi; [[ -s "$target_auth" ]] || die "Hindsight 独立 Codex auth.json 准备失败。"; chown "$runtime_uid:$runtime_gid" "$target_auth"; chmod 0600 "$target_auth"; write_env_value HINDSIGHT_CODEX_AUTH_DIR "$HINDSIGHT_SECRET_DIR"; log "已为 Hindsight 准备独立可写 Codex 凭据目录（UID:GID=${runtime_uid}:${runtime_gid}，目录 0700 / auth.json 0600）。"; }
if [[ "$PROVIDER" == openai-codex ]]; then install_codex_cli; CODEX_AUTH_DIR="$(get_env CODEX_HOME)"; CODEX_AUTH_DIR="${CODEX_AUTH_DIR:-$CODEX_AUTH_DIR_DEFAULT}"; mkdir -p "$CODEX_AUTH_DIR"; chmod 700 "$CODEX_AUTH_DIR"; CODEX_BIN="$(find_user_command codex || true)"; [[ -n "$CODEX_BIN" ]] || die "无法定位 Codex CLI。"; [[ -s "$CODEX_AUTH_DIR/auth.json" ]] || run_codex_oauth "$CODEX_BIN" "$CODEX_AUTH_DIR"; log "已检测到独立 Codex OAuth 凭据。"; else [[ -n "$API_KEY" ]] || die "当前 Provider=${PROVIDER} 需要 API Key。"; fi
IMAGE_TAG="$(get_env HINDSIGHT_IMAGE_TAG)"; IMAGE_TAG="${IMAGE_TAG:-latest}"; if [[ "$IMAGE_TAG" == latest && "$FREE_MB" -lt 12288 ]]; then die "Full Hindsight 镜像较大；当前 Docker 分区可用空间约 ${FREE_MB} MB，不足安全阈值 12GB。"; fi
if [[ "$PROVIDER" == openai-codex ]]; then prepare_hindsight_codex_auth "$CODEX_AUTH_DIR/auth.json" "$IMAGE_TAG"; fi
cd "$APP_DIR"; log "拉取 Hindsight 镜像。"; docker compose pull; log "启动 Hindsight。"; docker compose up -d --force-recreate; log "等待 API 启动（最多约 120 秒）。"; ok=0; for _ in $(seq 1 60); do if curl -fsS --max-time 2 http://127.0.0.1:8888/ >/dev/null 2>&1 || curl -fsS --max-time 2 http://127.0.0.1:8888/docs >/dev/null 2>&1; then ok=1; break; fi; sleep 2; done; if (( ok == 0 )); then docker compose ps; docker compose logs --tail=100 hindsight || true; die "Hindsight 容器已启动，但 API 健康检查未在等待时间内通过。"; fi; log "Hindsight API 已可从宿主机 127.0.0.1:8888 访问。"; docker compose ps
